name: For_My_Mini_Project

on: [push]
jobs:
  For-Project:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Installing pytest
        run: pip install pytest
      - name: Testing
        run: pytest -v --ff --tb=no --junitxml=path
      - name: Telegram Notifications (success)
        if: ${{ success() }}
        uses: "appleboy/telegram-action@master"
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: Все ок
      - name: Telegram Notifications (failure)
        if: ${{ failure() }}
        uses: "appleboy/telegram-action@master"
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Тест провален
          document: /home/runner/work/tp-hse-2022-hw/tp-hse-2022-hw/path

